"""btm-corekit: the shared symbolic kernel for SKILLs bundled scripts.
Import the whole surface from `btm_corekit`, never a submodule; a script
copied out of its workspace fails loudly at environment build.

An index is the exception, and imports as a module: `openalex.page` and
`crossref.page` are two calls that mean different things, and flattening
them would leave two names to invent."""

from __future__ import annotations

from btm_corekit.cli import (
    BATCH,
    ENTRY,
    MATCH,
    PAD_SCHEMA,
    REFS_SCHEMA,
    Commands,
    FromFile,
    FromStdin,
    Inline,
    Optional,
    Parser,
    Required,
    Slot,
    Source,
    View,
    add_slot,
    advise,
    at_least_one,
    content,
    dispatch,
    gated,
    read_batch,
    read_source,
    rejection,
    run_cli,
    source_of,
    spellings,
    text,
    wire_clean,
    wire_pad,
    wire_view,
)
from btm_corekit.indexes import arxiv, crossref, doi, openalex
from btm_corekit.indexes.work import (
    MaybeArxivId,
    MaybeDoi,
    Work,
    collapsed,
    normalize_arxiv_id,
    normalize_doi,
)
from btm_corekit.net.http import (
    build_client,
    client_for,
    download,
    get_bytes,
    status_failure,
    stream,
)
from btm_corekit.net.origin import (
    request_identity,
    user_agent,
)
from btm_corekit.net.wire import Upstream, decode, json_body
from btm_corekit.records.admission import Admission, Named, Pool, salvage, suggest
from btm_corekit.records.digest import CLUSTER_CAP, Digest, Item, digest
from btm_corekit.records.models import (
    ArxivId,
    Count,
    Doi,
    Keyword,
    Model,
    NonEmpty,
    Positive,
    Slug,
    Trimmed,
    diagnostics,
    dump,
    parse_model,
    parse_with,
    refuse,
)
from btm_corekit.report.channels import JSON, emit, signal
from btm_corekit.report.errors import CommandError, UpstreamError
from btm_corekit.report.invariants import demand, require
from btm_corekit.report.verdicts import Diagnostic
from btm_corekit.store.cache import cache_dir, cache_slot, clean_cache
from btm_corekit.store.clock import now_iso
from btm_corekit.store.eventlog import MAX_EVENTS, EventLog
from btm_corekit.store.fsio import (
    append_jsonl,
    count_lines,
    read_jsonl,
    state_root,
    tree_bytes,
    write_atomic,
)
from btm_corekit.store.identifiers import (
    Ambiguous,
    Exact,
    NoMatch,
    Recovered,
    band_signal,
    eliminate,
    keywords_of,
    mint,
    resolve,
    slugify,
    suffix,
)
from btm_corekit.store.pad import (
    compile_match,
    jot,
    pad_entries,
    pad_ids,
    recall,
)
from btm_corekit.store.sessions import SessionStore
from btm_corekit.text import (
    ASCII_WORD,
    ascii_words,
    bracketed,
    collapse_whitespace,
    digit_run,
    heading_words,
    is_digits,
    keep_table,
    prefixed_number,
    runs,
    strip_code,
    strip_tags,
)

__all__ = [
    "ASCII_WORD",
    "BATCH",
    "CLUSTER_CAP",
    "ENTRY",
    "JSON",
    "MATCH",
    "MAX_EVENTS",
    "PAD_SCHEMA",
    "REFS_SCHEMA",
    "Admission",
    "Ambiguous",
    "ArxivId",
    "CommandError",
    "Commands",
    "Count",
    "Diagnostic",
    "Digest",
    "Doi",
    "EventLog",
    "Exact",
    "FromFile",
    "FromStdin",
    "Inline",
    "Item",
    "Keyword",
    "MaybeArxivId",
    "MaybeDoi",
    "Model",
    "Named",
    "NoMatch",
    "NonEmpty",
    "Optional",
    "Parser",
    "Pool",
    "Positive",
    "Recovered",
    "Required",
    "SessionStore",
    "Slot",
    "Slug",
    "Source",
    "Trimmed",
    "Upstream",
    "UpstreamError",
    "View",
    "Work",
    "add_slot",
    "advise",
    "append_jsonl",
    "arxiv",
    "ascii_words",
    "at_least_one",
    "band_signal",
    "bracketed",
    "build_client",
    "cache_dir",
    "cache_slot",
    "clean_cache",
    "client_for",
    "collapse_whitespace",
    "collapsed",
    "compile_match",
    "content",
    "count_lines",
    "crossref",
    "decode",
    "demand",
    "diagnostics",
    "digest",
    "digit_run",
    "dispatch",
    "doi",
    "download",
    "dump",
    "eliminate",
    "emit",
    "gated",
    "get_bytes",
    "heading_words",
    "is_digits",
    "jot",
    "json_body",
    "keep_table",
    "keywords_of",
    "mint",
    "normalize_arxiv_id",
    "normalize_doi",
    "now_iso",
    "openalex",
    "pad_entries",
    "pad_ids",
    "parse_model",
    "parse_with",
    "prefixed_number",
    "read_batch",
    "read_jsonl",
    "read_source",
    "recall",
    "refuse",
    "rejection",
    "request_identity",
    "require",
    "resolve",
    "run_cli",
    "runs",
    "salvage",
    "signal",
    "slugify",
    "source_of",
    "spellings",
    "state_root",
    "status_failure",
    "stream",
    "strip_code",
    "strip_tags",
    "suffix",
    "suggest",
    "text",
    "tree_bytes",
    "user_agent",
    "wire_clean",
    "wire_pad",
    "wire_view",
    "write_atomic",
]
