"""btm-corekit: the shared symbolic kernel for SKILLs bundled scripts.
Import the whole surface from `btm_corekit`, never a submodule; a script
copied out of its workspace fails loudly at environment build.

An index is the exception, and imports as a module: `openalex.page` and
`crossref.page` are two calls that mean different things, and flattening
them would leave two names to invent. A member reaching an index by name
goes through `INDEXES` and the registry's `search`, `references`,
`citations`, and `passages` instead, and never touches the module."""

from __future__ import annotations

from btm_corekit.cli import (
    BATCH,
    MATCH,
    PAD_SCHEMA,
    REFS_SCHEMA,
    Commands,
    Optional,
    Parser,
    Required,
    View,
    add_slot,
    content,
    dispatch,
    gated,
    rejection,
    run_cli,
    text,
    wire_clean,
    wire_limit,
    wire_pad,
    wire_view,
)
from btm_corekit.indexes import arxiv, crossref, doi, openalex
from btm_corekit.indexes.registry import (
    INDEXES,
    citations,
    having,
    passages,
    references,
    search,
)
from btm_corekit.indexes.work import (
    ByArxiv,
    ByDoi,
    ByNative,
    MaybeArxivId,
    MaybeDoi,
    Passage,
    Ref,
    Window,
    Work,
    collapsed,
    normalize_arxiv_id,
    normalize_doi,
)
from btm_corekit.net.http import (
    build_client,
    client_for,
    download,
    get_bytes,
    stream,
)
from btm_corekit.net.wire import Upstream, json_body
from btm_corekit.records.admission import Admission, Named, Pool, salvage, suggest
from btm_corekit.records.digest import CLUSTER_CAP, Item, digest
from btm_corekit.records.models import (
    Count,
    Doi,
    Model,
    NonEmpty,
    Positive,
    Slug,
    Trimmed,
    dump,
    parse_model,
    parse_with,
    refuse,
)
from btm_corekit.report.channels import JSON, emit, signal
from btm_corekit.report.errors import CommandError, UpstreamError
from btm_corekit.report.invariants import demand, require
from btm_corekit.report.verdicts import Diagnostic
from btm_corekit.store.cache import cache_slot, clean_cache
from btm_corekit.store.clock import now_iso
from btm_corekit.store.eventlog import MAX_EVENTS, EventLog, Stamped
from btm_corekit.store.fsio import (
    append_jsonl,
    count_lines,
    read_jsonl,
    remove_tree,
    state_root,
    write_atomic,
)
from btm_corekit.store.identifiers import (
    mint,
    slugify,
)
from btm_corekit.store.pad import (
    compile_match,
    pad_entries,
    pad_ids,
)
from btm_corekit.store.sessions import (
    LIT_REVIEW_CORPUS,
    LIT_REVIEW_SESSIONS,
    SessionStore,
)
from btm_corekit.text import (
    ASCII_WORD,
    ascii_words,
    blanked,
    bracketed,
    collapse_whitespace,
    digit_run,
    heading_words,
    is_digits,
    keep_table,
    prefixed_number,
    runs,
    strip_code,
)

__all__ = [
    "ASCII_WORD",
    "BATCH",
    "CLUSTER_CAP",
    "INDEXES",
    "JSON",
    "LIT_REVIEW_CORPUS",
    "LIT_REVIEW_SESSIONS",
    "MATCH",
    "MAX_EVENTS",
    "PAD_SCHEMA",
    "REFS_SCHEMA",
    "Admission",
    "ByArxiv",
    "ByDoi",
    "ByNative",
    "CommandError",
    "Commands",
    "Count",
    "Diagnostic",
    "Doi",
    "EventLog",
    "Item",
    "MaybeArxivId",
    "MaybeDoi",
    "Model",
    "Named",
    "NonEmpty",
    "Optional",
    "Parser",
    "Passage",
    "Pool",
    "Positive",
    "Ref",
    "Required",
    "SessionStore",
    "Slug",
    "Stamped",
    "Trimmed",
    "Upstream",
    "UpstreamError",
    "View",
    "Window",
    "Work",
    "add_slot",
    "append_jsonl",
    "arxiv",
    "ascii_words",
    "blanked",
    "bracketed",
    "build_client",
    "cache_slot",
    "citations",
    "clean_cache",
    "client_for",
    "collapse_whitespace",
    "collapsed",
    "compile_match",
    "content",
    "count_lines",
    "crossref",
    "demand",
    "digest",
    "digit_run",
    "dispatch",
    "doi",
    "download",
    "dump",
    "emit",
    "gated",
    "get_bytes",
    "having",
    "heading_words",
    "is_digits",
    "json_body",
    "keep_table",
    "mint",
    "normalize_arxiv_id",
    "normalize_doi",
    "now_iso",
    "openalex",
    "pad_entries",
    "pad_ids",
    "parse_model",
    "parse_with",
    "passages",
    "prefixed_number",
    "read_jsonl",
    "references",
    "refuse",
    "rejection",
    "remove_tree",
    "require",
    "run_cli",
    "runs",
    "salvage",
    "search",
    "signal",
    "slugify",
    "state_root",
    "stream",
    "strip_code",
    "suggest",
    "text",
    "wire_clean",
    "wire_limit",
    "wire_pad",
    "wire_view",
    "write_atomic",
]
