"""btm-corekit: the shared symbolic kernel for SKILLs bundled scripts.
Import the whole surface from `btm_corekit`, never a submodule; a script
copied out of its workspace fails loudly at environment build."""

from __future__ import annotations

from btm_corekit.admission import Admission, Named, Pool, salvage, suggest
from btm_corekit.channels import JSON, emit, signal
from btm_corekit.cli import (
    PAD_SCHEMA,
    REFS_SCHEMA,
    Commands,
    Outcome,
    Parser,
    View,
    advise,
    content,
    dispatch,
    gated,
    read_batch,
    rejection,
    run_cli,
    text_source,
    wire_clean,
    wire_pad,
    wire_view,
)
from btm_corekit.clock import now_iso
from btm_corekit.digest import Cluster, Digest, Item, digest
from btm_corekit.errors import CommandError, UpstreamError
from btm_corekit.eventlog import MAX_EVENTS, EventLog
from btm_corekit.fsio import (
    append_jsonl,
    count_lines,
    read_jsonl,
    state_root,
    tree_bytes,
    write_atomic,
)
from btm_corekit.http import (
    HTTP_BAD_REQUEST,
    HTTP_SERVER_ERROR,
    HTTP_TOO_MANY_REQUESTS,
    build_client,
    download,
    get_bytes,
    openalex_params,
    openalex_query,
    status_failure,
    stream,
)
from btm_corekit.identifiers import (
    KEYWORD_RANGE,
    Ambiguous,
    Exact,
    NoMatch,
    Recovered,
    Resolution,
    band_signal,
    eliminate,
    is_pathlike,
    keywords_of,
    mint,
    resolve,
    slugify,
    suffix,
)
from btm_corekit.invariants import demand, parse_enum, require
from btm_corekit.models import (
    ArxivId,
    Count,
    Doi,
    Keyword,
    Model,
    NonEmpty,
    Positive,
    Slug,
    Trimmed,
    diagnostics,
    dump,
    parse_model,
    parse_with,
    refuse,
)
from btm_corekit.origin import (
    OPENALEX_KEY_ENV,
    Contact,
    CustomAgent,
    Keyed,
    OpenAlexAccess,
    RequestIdentity,
    Trial,
    openalex_access,
    polite_params,
    request_identity,
    user_agent,
)
from btm_corekit.pad import compile_match, jot, pad_body, pad_entries, pad_ids, recall
from btm_corekit.sessions import Created, SessionStore
from btm_corekit.text import (
    ASCII_WORD,
    ascii_words,
    bracketed,
    collapse_whitespace,
    digit_run,
    heading_words,
    is_digits,
    keep_table,
    prefixed_number,
    runs,
    strip_tags,
)
from btm_corekit.verdicts import Diagnostic

__all__ = [
    "ASCII_WORD",
    "HTTP_BAD_REQUEST",
    "HTTP_SERVER_ERROR",
    "HTTP_TOO_MANY_REQUESTS",
    "JSON",
    "KEYWORD_RANGE",
    "MAX_EVENTS",
    "OPENALEX_KEY_ENV",
    "PAD_SCHEMA",
    "REFS_SCHEMA",
    "Admission",
    "Ambiguous",
    "ArxivId",
    "Cluster",
    "CommandError",
    "Commands",
    "Contact",
    "Count",
    "Created",
    "CustomAgent",
    "Diagnostic",
    "Digest",
    "Doi",
    "EventLog",
    "Exact",
    "Item",
    "Keyed",
    "Keyword",
    "Model",
    "Named",
    "NoMatch",
    "NonEmpty",
    "OpenAlexAccess",
    "Outcome",
    "Parser",
    "Pool",
    "Positive",
    "Recovered",
    "RequestIdentity",
    "Resolution",
    "SessionStore",
    "Slug",
    "Trial",
    "Trimmed",
    "UpstreamError",
    "View",
    "advise",
    "append_jsonl",
    "ascii_words",
    "band_signal",
    "bracketed",
    "build_client",
    "collapse_whitespace",
    "compile_match",
    "content",
    "count_lines",
    "demand",
    "diagnostics",
    "digest",
    "digit_run",
    "dispatch",
    "download",
    "dump",
    "eliminate",
    "emit",
    "gated",
    "get_bytes",
    "heading_words",
    "is_digits",
    "is_pathlike",
    "jot",
    "keep_table",
    "keywords_of",
    "mint",
    "now_iso",
    "openalex_access",
    "openalex_params",
    "openalex_query",
    "pad_body",
    "pad_entries",
    "pad_ids",
    "parse_enum",
    "parse_model",
    "parse_with",
    "polite_params",
    "prefixed_number",
    "read_batch",
    "read_jsonl",
    "recall",
    "refuse",
    "rejection",
    "request_identity",
    "require",
    "resolve",
    "run_cli",
    "runs",
    "salvage",
    "signal",
    "slugify",
    "state_root",
    "status_failure",
    "stream",
    "strip_tags",
    "suffix",
    "suggest",
    "text_source",
    "tree_bytes",
    "user_agent",
    "wire_clean",
    "wire_pad",
    "wire_view",
    "write_atomic",
]
