"""Pure renderers: one EnvDelta, three consumers.

The same value becomes activate.sh (POSIX), activate.ps1 (PowerShell), and
the literal process environment used for verification probes. Because all
three come from one merged delta, the environment the probes proved is the
environment activation grants; the renderers cannot drift apart.
"""

from __future__ import annotations

import shlex
import os

from .model import OS, EnvDelta, Host

# The system tail kept on PATH. Deliberately short: the point of activation
# is that the environment, not the caller's PATH, supplies the toolchain.
_POSIX_TAIL = ("/usr/local/bin", "/usr/bin", "/bin", "/usr/sbin", "/sbin")


def path_value(delta: EnvDelta, host: Host, base: str | None = None) -> str:
    sep = ";" if host.os is OS.WINDOWS else ":"
    tail = (
        base
        if base is not None
        else ("" if host.os is OS.WINDOWS else sep.join(_POSIX_TAIL))
    )
    entries = [str(p) for p in delta.path]
    return sep.join([*entries, tail] if tail else entries)


def render_sh(delta: EnvDelta, host: Host) -> str:
    lines = [
        "#!/bin/sh",
        "# Generated by envctl. Source it: . <root>/activate.sh",
        "# Idempotent: every value is absolute and derived from the root.",
    ]
    exported = {name for name, _ in delta.vars}
    lines += [f"unset {name}" for name in sorted(delta.unset - exported)]
    lines += [f"export {name}={shlex.quote(value)}" for name, value in delta.vars]
    lines.append(f"export PATH={shlex.quote(path_value(delta, host))}")
    return "\n".join(lines) + "\n"


def _ps_quote(value: str) -> str:
    return "'" + value.replace("'", "''") + "'"


def render_ps1(delta: EnvDelta, host: Host) -> str:
    # Windows isolation is partial by design: the caller's PATH stays as the
    # tail because SystemRoot tooling must remain reachable.
    lines = ["# Generated by envctl. Dot-source it: . <root>\\activate.ps1"]
    exported = {name for name, _ in delta.vars}
    lines += [
        f"Remove-Item Env:{name} -ErrorAction SilentlyContinue"
        for name in sorted(delta.unset - exported)
    ]
    lines += [f"$env:{name} = {_ps_quote(value)}" for name, value in delta.vars]
    prepends = path_value(delta, host, base="")
    lines.append(f"$env:Path = {_ps_quote(prepends)} + ';' + $env:Path")
    return "\n".join(lines) + "\n"


def realize(delta: EnvDelta, host: Host) -> dict[str, str]:
    """The probe environment: what a shell would hold after sourcing the
    activation script, built directly rather than through a shell."""
    if host.os is OS.WINDOWS:
        # os.environ upper-cases its keys on windows, so PATH is the only
        # spelling present to inherit from and the only one worth writing back.
        env = {k: v for k, v in os.environ.items() if k not in delta.unset}
        env.update(dict(delta.vars))
        env["PATH"] = path_value(delta, host, base=os.environ.get("PATH", ""))
        return env
    env = dict( delta.vars )
    env["PATH"] = path_value(delta, host)
    return env
