"""Pure renderers: one EnvDelta, three consumers.

The same value becomes activate.sh (POSIX), activate.ps1 (PowerShell), and
the literal process environment used for verification probes. Because all
three come from one merged delta, the environment the probes proved is the
environment activation grants; the renderers cannot drift apart.
"""

from __future__ import annotations

import os
import shlex

from btm_setup_env.model import OS, EnvDelta, Host

# Keep system tools reachable after replacing the caller's PATH.
_POSIX_TAIL = ("/usr/local/bin", "/usr/bin", "/bin", "/usr/sbin", "/sbin")


def path_value(delta: EnvDelta, host: Host, base: str | None = None) -> str:
    sep = ";" if host.os is OS.WINDOWS else ":"
    tail = (
        base
        if base is not None
        else ("" if host.os is OS.WINDOWS else sep.join(_POSIX_TAIL))
    )
    entries = [str(p) for p in delta.path]
    return sep.join([*entries, tail] if tail else entries)


def render_sh(delta: EnvDelta, host: Host) -> str:
    lines = [
        "#!/bin/sh",
        "# Generated by btm-setup-env. Source it: . <root>/activate.sh",
        "# Idempotent: every value is absolute and derived from the root.",
    ]
    exported = {name for name, _ in delta.vars}
    lines += [f"unset {name}" for name in sorted(delta.unset - exported)]
    lines += [f"export {name}={shlex.quote(value)}" for name, value in delta.vars]
    lines.append(f"export PATH={shlex.quote(path_value(delta, host))}")
    return "\n".join(lines) + "\n"


def _ps_quote(value: str) -> str:
    return "'" + value.replace("'", "''") + "'"


def render_ps1(delta: EnvDelta, host: Host) -> str:
    # Keep the caller's PATH tail so SystemRoot tools remain reachable.
    lines = ["# Generated by btm-setup-env. Dot-source it: . <root>\\activate.ps1"]
    exported = {name for name, _ in delta.vars}
    lines += [
        f"Remove-Item Env:{name} -ErrorAction SilentlyContinue"
        for name in sorted(delta.unset - exported)
    ]
    lines += [f"$env:{name} = {_ps_quote(value)}" for name, value in delta.vars]
    prepends = path_value(delta, host, base="")
    lines.append(f"$env:Path = {_ps_quote(prepends)} + ';' + $env:Path")
    return "\n".join(lines) + "\n"


def realize(delta: EnvDelta, host: Host) -> dict[str, str]:
    """The probe environment: what a shell would hold after sourcing the
    activation script, built directly rather than through a shell."""
    if host.os is OS.WINDOWS:
        # Windows normalizes environment keys; preserve inherited PATH spelling.
        env = {k: v for k, v in os.environ.items() if k not in delta.unset}
        env.update(dict(delta.vars))
        env["PATH"] = path_value(delta, host, base=os.environ.get("PATH", ""))
        return env
    env = dict(delta.vars)
    env["PATH"] = path_value(delta, host)
    return env
